default:
	pdflatex openproblem_report
	pdflatex openproblem_report

bib:
	pdflatex openproblem_report
	bibtex openproblem_report
	pdflatex openproblem_report
	pdflatex openproblem_report

clean:
	rm *.aux *.bbl *.blg *.log *.out
